# Generated by Django 5.0.1 on 2024-01-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('difficulty', models.CharField(max_length=20)),
                ('prep', models.IntegerField()),
                ('cooking', models.IntegerField()),
                ('total', models.IntegerField()),
                ('ingredients', models.CharField(max_length=9999)),
                ('instruction', models.CharField(max_length=9999)),
            ],
        ),
    ]
